name: pre-commit

on:
  push:
    branches:
      - '*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  GITHUB_USER: th3w1zard1
  GITHUB_REPOSITORY: KOTORModSync

defaults:
  run:
    shell: bash

jobs:
  pre-commit-csharp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # SDK Version to use

    # Format the output of dotnet format
    - name: Add dotnet-format problem matcher
      uses: xt0rted/dotnet-format-problem-matcher@v1

    # Install dotnet format as a global tool
    - name: Install dotnet format
      run: dotnet tool update --global dotnet-format

    # Run dotnet format
    - name: Run dotnet format
      run: dotnet format --severity info

    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v2023.1.0
      
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

    - name: Commit changes
      run: |
        git config --global user.name 'Pre-commit Style Enforcer'
        git config --global user.email 'precommit_workflow@githubactions.com'
        git add .
        git diff-index --quiet HEAD || git commit -m "Auto-format code using dotnet format" && git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
