name: pre-commit

on:
  push:
    branches:
      - '*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  GITHUB_USER: th3w1zard1
  GITHUB_REPOSITORY: KOTORModSync

defaults:
  run:
    shell: bash

jobs:
  pre-commit-csharp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # SDK Version to use

    # Format the output of dotnet format
    - name: Add dotnet-format problem matcher
      uses: xt0rted/dotnet-format-problem-matcher@v1

    # Install dotnet format as a global tool
    - name: Install dotnet format
      run: dotnet tool update --global dotnet-format

    # Run dotnet format
    - name: Run dotnet format
      run: dotnet format --severity info

    - name: Setup ReSharper Command Line Tools
      uses: goit/setup-resharper@v2.0.1
      with:
        version: '2021.1'

    - name: Clean up code
      run: cleanupcode.sh ${{ github.workspace }}/*.sln

    - name: Find duplicate code
      run: dupFinder.sh "**/*.cs" -o=.github/resharper_duplicatefinder_$(date +\%Y-\%m-\%d).log

    - name: Find Solution File
      id: solution
      run: |
        solutionFile=$(find . -name "*.sln" -type f -print -quit)
        echo "::set-output name=solution_path::$solutionFile"

    - name: Analyze code
      run: ./InspectCode.sh ${{ steps.solution.outputs.solution_path }} -o=TestResults/resharper_inspect_$(date +\%Y-\%m-\%d).log


    - name: Commit changes
      run: |
        git config --global user.name 'Pre-commit Style Enforcer'
        git config --global user.email 'precommit_workflow@githubactions.com'
        git add .
        git diff-index --quiet HEAD || git commit -m "Auto-format code using dotnet format" && git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
